<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\OrientiringService.Domain\OrientiringService.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Maps\" />
	  <Folder Include="Users\" />
	</ItemGroup>
</Project>
